#!/bin/sh

start() {
    /usr/bin/batd
}

stop() {
    kill -TERM "$(cat /var/run/batd.lock)"
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)   start ;;
    stop)    stop ;;
    restart) restart ;;
    *) echo "Usage: $0 {start|stop|restart}" ;;
esac
